import type { Metadata } from "next";

let id;
export default function ProductLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { id: string };
}) {
  id = params.id;
  console.log(id);
  return (
    <>
      {children}
      {params.id}
    </>
  );
}

export const metadata: Metadata = {
  title: `KarT | ${id}`,
  description: "Generated by Thanh Nguyen",
};
