import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@/app/_assets/libs/style.css";
import "@/app/_assets/libs/animate.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "KarT | Skateboard Website",
  description: "Generated by Thanh Nguyen",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="shortcut icon"
          type="image/x-icon"
          href="/images/favicon.ico"
        />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/images/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/images/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/images/favicon-16x16.png"
        />
      </head>
      <body className={inter.className} suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  );
}
