import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "KarT | Entire Products ",
  description: "Generated by Thanh Nguyen",
};

export default function ProductsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
